os:
- linux
language: python
python:
- 3.6
install:
- pip install -r requirements.txt

jobs:
  include:
    - stage: tests

      script:
      - pytest --cov=apps --cov-config=.coveragerc
      name: pytestq

    - script: python -m black apps --line-length=88
      name: pep8

    - script: flake8
      name: flake8
